version: '2'

services:     
  ttnode:
    image: ericwang2006/ttnode
    container_name: ttnode
    hostname: ttnode1
    #privileged: true
    cap_add:
      - ALL
    restart: always
    mac_address: C2:F2:9C:C5:B2:94
    dns: 114.114.114.114
    networks: 
      macvlan:
        ipv4_address: 192.168.1.10
    volumes:
      - /data/hdd/ttnode:/mnts

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1