version: "2.1"
services:
  github:
    build: ./web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.github.loadbalancer.server.port=80"
      - "traefik.http.routers.github.rule=Host(`github.example.org`)"
      - "traefik.http.routers.github.entrypoints=websecure"
      - "traefik.http.routers.github.tls.certresolver=myresolver"
    networks:
      - proxy-tier
      
networks:
  proxy-tier:
    external:
      name: traefik
